// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;
using Web.Data.Context;

namespace Web.Migrations
{
    [DbContext(typeof(MariaDbContext))]
    [Migration("20181227101239_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Web.Domain.ContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("content_types");
                });

            modelBuilder.Entity("Web.Domain.Fabric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<int>("ContentTypeId")
                        .HasColumnName("content_type_id")
                        .HasColumnType("int(11)");

                    b.Property<sbyte>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("count")
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValueSql("'16'");

                    b.Property<int>("FabricTypeId")
                        .HasColumnName("fabric_type_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)");

                    b.Property<sbyte>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("priority")
                        .HasColumnType("tinyint(4)")
                        .HasDefaultValueSql("'3'");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name", "Count");

                    b.HasIndex("ContentTypeId")
                        .HasName("fk_content_type_id");

                    b.HasIndex("FabricTypeId")
                        .HasName("fk_fabric_type_id");

                    b.ToTable("fabrics");
                });

            modelBuilder.Entity("Web.Domain.FabricItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("ColorId")
                        .IsRequired()
                        .HasColumnName("color_id")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnName("color_name")
                        .HasColumnType("varchar(64)");

                    b.Property<int>("FabricId")
                        .HasColumnName("fabric_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnName("sku")
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("FabricId")
                        .HasName("fk_fabric_id");

                    b.ToTable("fabric_items");
                });

            modelBuilder.Entity("Web.Domain.FabricOption", b =>
                {
                    b.Property<int>("PatternId")
                        .HasColumnName("pattern_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("FabricItemId")
                        .HasColumnName("fabric_item_id")
                        .HasColumnType("int(11)");

                    b.HasKey("PatternId", "FabricItemId");

                    b.HasIndex("FabricItemId")
                        .HasName("fk_fabric_option_fabric_item_id");

                    b.ToTable("fabric_options");
                });

            modelBuilder.Entity("Web.Domain.FabricType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("fabric_types");
                });

            modelBuilder.Entity("Web.Domain.Kit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<int?>("AuthorId")
                        .HasColumnName("author_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("ColorsCount")
                        .HasColumnName("colors_count")
                        .HasColumnType("int(11)");

                    b.Property<int>("FabricItemId")
                        .HasColumnName("fabric_item_id")
                        .HasColumnType("int(11)");

                    b.Property<sbyte>("HeightSm")
                        .HasColumnName("height_sm")
                        .HasColumnType("tinyint(4)");

                    b.Property<sbyte>("HeightStitches")
                        .HasColumnName("height_stitches")
                        .HasColumnType("tinyint(4)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnName("image")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnName("item")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnName("link")
                        .HasColumnType("varchar(256)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnName("manufacturer_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("ThreadManufacturerId")
                        .HasColumnName("thread_manufacturer_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(64)");

                    b.Property<sbyte>("WidthSm")
                        .HasColumnName("width_sm")
                        .HasColumnType("tinyint(4)");

                    b.Property<sbyte>("WidthStitches")
                        .HasColumnName("width_stitches")
                        .HasColumnType("tinyint(4)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Title", "ManufacturerId");

                    b.HasIndex("AuthorId")
                        .HasName("fk_kit_author_id");

                    b.HasIndex("FabricItemId")
                        .HasName("fk_kit_fabric_item_id");

                    b.HasIndex("ManufacturerId")
                        .HasName("fk_kit_manufacturer_id");

                    b.HasIndex("ThreadManufacturerId")
                        .HasName("fk_kit_thread_manufacturer_id");

                    b.ToTable("kits");
                });

            modelBuilder.Entity("Web.Domain.KitManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("kit_manufacturers");
                });

            modelBuilder.Entity("Web.Domain.Pattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<int>("AuthorId")
                        .HasColumnName("author_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("ColorsCount")
                        .HasColumnName("colors_count")
                        .HasColumnType("int(11)");

                    b.Property<sbyte>("Height")
                        .HasColumnName("height")
                        .HasColumnType("tinyint(4)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnName("image")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnName("item")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnName("link")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(64)");

                    b.Property<sbyte>("Width")
                        .HasColumnName("width")
                        .HasColumnType("tinyint(4)");

                    b.HasKey("Id");

                    b.HasAlternateKey("AuthorId", "Title");

                    b.HasIndex("AuthorId")
                        .HasName("fk_pattern_author_id");

                    b.ToTable("patterns");
                });

            modelBuilder.Entity("Web.Domain.PatternAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("pattern_authors");
                });

            modelBuilder.Entity("Web.Domain.ThreadColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("ColorId")
                        .IsRequired()
                        .HasColumnName("color_id")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnName("color_name")
                        .HasColumnType("varchar(64)");

                    b.Property<sbyte>("Length")
                        .HasColumnName("length")
                        .HasColumnType("tinyint(4)");

                    b.Property<int>("ManufacturerId")
                        .HasColumnName("manufacturer_id")
                        .HasColumnType("int(11)");

                    b.Property<string>("RgbColor")
                        .HasColumnName("rgb_color")
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnName("sku")
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasAlternateKey("ManufacturerId", "ColorId");

                    b.HasIndex("ManufacturerId")
                        .HasName("fk_manufacturer_id");

                    b.ToTable("thread_colors");
                });

            modelBuilder.Entity("Web.Domain.ThreadColorOption", b =>
                {
                    b.Property<int>("PatternId")
                        .HasColumnName("pattern_id")
                        .HasColumnType("int(11)");

                    b.Property<int>("ThreadColorId")
                        .HasColumnName("thread_color_id")
                        .HasColumnType("int(11)");

                    b.Property<decimal?>("RequiredLength")
                        .HasColumnName("required_length")
                        .HasColumnType("decimal(5,2) unsigned zerofill");

                    b.HasKey("PatternId", "ThreadColorId");

                    b.HasIndex("ThreadColorId")
                        .HasName("fk_thread_color_option_thread_color_id");

                    b.ToTable("thread_color_options");
                });

            modelBuilder.Entity("Web.Domain.ThreadManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("thread_manufacturers");
                });

            modelBuilder.Entity("Web.Domain.Fabric", b =>
                {
                    b.HasOne("Web.Domain.ContentType", "ContentType")
                        .WithMany("Fabrics")
                        .HasForeignKey("ContentTypeId")
                        .HasConstraintName("fk_content_type_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Domain.FabricType", "FabricType")
                        .WithMany("Fabrics")
                        .HasForeignKey("FabricTypeId")
                        .HasConstraintName("fk_fabric_type_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Domain.FabricItem", b =>
                {
                    b.HasOne("Web.Domain.Fabric", "Fabric")
                        .WithMany("FabricItems")
                        .HasForeignKey("FabricId")
                        .HasConstraintName("fk_fabric_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Domain.FabricOption", b =>
                {
                    b.HasOne("Web.Domain.FabricItem", "FabricItem")
                        .WithMany("FabricOptions")
                        .HasForeignKey("FabricItemId")
                        .HasConstraintName("fk_fabric_option_fabric_item_id");

                    b.HasOne("Web.Domain.Pattern", "Pattern")
                        .WithMany("FabricOptions")
                        .HasForeignKey("PatternId")
                        .HasConstraintName("fk_fabric_option_pattern_id");
                });

            modelBuilder.Entity("Web.Domain.Kit", b =>
                {
                    b.HasOne("Web.Domain.PatternAuthor", "Author")
                        .WithMany("Kits")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_kit_author_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Domain.FabricItem", "FabricItem")
                        .WithMany("Kits")
                        .HasForeignKey("FabricItemId")
                        .HasConstraintName("fk_kit_fabric_item_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Domain.KitManufacturer", "Manufacturer")
                        .WithMany("Kits")
                        .HasForeignKey("ManufacturerId")
                        .HasConstraintName("fk_kit_manufacturer_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Web.Domain.ThreadManufacturer", "ThreadManufacturer")
                        .WithMany("Kits")
                        .HasForeignKey("ThreadManufacturerId")
                        .HasConstraintName("fk_kit_thread_manufacturer_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Domain.Pattern", b =>
                {
                    b.HasOne("Web.Domain.PatternAuthor", "Author")
                        .WithMany("Patterns")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("fk_pattern_author_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Domain.ThreadColor", b =>
                {
                    b.HasOne("Web.Domain.ThreadManufacturer", "Manufacturer")
                        .WithMany("ThreadColors")
                        .HasForeignKey("ManufacturerId")
                        .HasConstraintName("fk_manufacturer_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Domain.ThreadColorOption", b =>
                {
                    b.HasOne("Web.Domain.Pattern", "Pattern")
                        .WithMany("ThreadColorOptions")
                        .HasForeignKey("PatternId")
                        .HasConstraintName("fk_thread_color_option_pattern_id");

                    b.HasOne("Web.Domain.ThreadColor", "ThreadColor")
                        .WithMany("ThreadColorOptions")
                        .HasForeignKey("ThreadColorId")
                        .HasConstraintName("fk_thread_color_option_thread_color_id");
                });
#pragma warning restore 612, 618
        }
    }
}
